### ISSUE TITLE
Project directory not configured for flask applications and vercel hosting.

### ISSUE THREAD

**Issue by KrishnashishMunshi** [Deeptig9138/Speed-Typing-Test#7]
The project directory doesn't follow flask configurations hence, the hosted website on vercel is non-responsive and it yields jinja exception error when running on local device.

**Comment by KrishnashishMunshi** [comment]
@Deeptig9138 Please assign me this issue, I can configure the directory to flask convention and also add the files required for hosting it successfully on vercel.

**Comment by Deeptig9138** [comment]
done

**Comment by ShashiSingh8434** [comment]
> The project directory doesn't follow flask configurations hence, the hosted website on vercel is non-responsive and it yields jinja exception error when running on local device.

Hi, I am Shashi Singh I had raised similar issue of project directory configuration which i think i have kind of solved .you can check it out by cloning my forked project for verification <https://github.com/ShashiSingh8434/Speed-Typing-Test-Forked> you can follow the steps which I have written down in readme file.

But you can proceed with "vercel hosting" part because i think it is still not responsive to website,

If I made any assumptions please forgive me. But I think you should Check out my forked project for clarification.
To contact me you can mail me at <shashisingh843454@gmail.com> for fast respose.

Thank You.

**Comment by KrishnashishMunshi** [comment]
> done

I have done the necessary changes and created a pull request. Kindly check.

**Comment by ShashiSingh8434** [comment]
Okay

**Comment by Deeptig9138** [comment]
Hey @KrishnashishMunshi . Can you help me with vercel deployment. I am very new to this and still dont know how things work around this. Could you take a look because a lot of change has happened and they have not been updated on website.

**Comment by KrishnashishMunshi** [comment]
I see ,understood, I will create a new issue regarding it and try to resolve it as soon as possible. You could close this issue.
